OASE ConclusionのPyPyバージョン固定化

diff --git a/ita_root/ita_by_oase_conclusion/Dockerfile b/ita_root/ita_by_oase_conclusion/Dockerfile
--- a/ita_root/ita_by_oase_conclusion/Dockerfile
+++ b/ita_root/ita_by_oase_conclusion/Dockerfile
@@ -34,7 +34,10 @@ ENV EVALUATE_LATENT_INFINITE_LOOP_LIMIT=1000
 # ハングアップ監視用ファイル
 ENV FILE_PATH_LIVENESS=/tmp/liveness
 
-ENV PATH /opt/pypy/bin:$PATH
+# Docker公式のPyPyイメージでは/opt/pypy/binを優先している
+# そうするとpython3コマンドがPyPy固定化してしまう
+# alternativesを使いたいので/opt/pypy/binの優先を下げる
+ENV PATH ${PATH}:/opt/pypy/bin
 
 RUN --mount=type=secret,id=host_certificate_file,dst=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem \
     set -eux; \
@@ -46,7 +49,6 @@ RUN --mount=type=secret,id=host_certificate_file,dst=/etc/pki/ca-trust/extracted
     zip \
     unzip \
     bzip2 \
-    jq \
     python3.11 \
     python3.11-devel \
     python3.11-pip \
@@ -56,43 +58,34 @@ RUN --mount=type=secret,id=host_certificate_file,dst=/etc/pki/ca-trust/extracted
 #\
 # start pypy install  
 RUN set -eux; \
+# PyPyのバージョンはPyPyバージョン("v"major.minor.patch)とPythonバージョン(major.minor)の2つを持ちます
+# 例: PyPyバージョンv7.3.20ではPythonバージョンの3.11と2.7の2つを実装しています
+# PyPyを変更する場合はそれぞれpypy_version("v"を取り除くこと)とpython_versionを変更してください
+# どのようなバージョンがあるかは https://downloads.python.org/pypy/ を参照してください
     python_version="3.11" \
-&&  pypy_version="7.3" \
-&&  platform="linux" \
+&&  pypy_version="7.3.20" \
 &&  unameArch="$(uname -m)" \
 &&  case "$unameArch" in \
-        'x86_64' | 'x64' | 'amd64') arch='x64'; ;; \
-        'aarch64') arch='aarch64'; ;; \
-        'i686' | 'i386' | 'x86') arch='i686'; ;; \
-        *) echo >&2 "error: current architecture ($unameArch) does not have a corresponding PyPy binary release"; exit 1 ;; \
+        'x86_64' | 'x64' | 'amd64') \
+            pypy_download_url="https://downloads.python.org/pypy/pypy${python_version}-v${pypy_version}-linux64.tar.bz2"; \
+        ;; \
+        'aarch64') \
+            pypy_download_url="https://downloads.python.org/pypy/pypy${python_version}-v${pypy_version}-aarch64.tar.bz2"; \
+        ;; \
+        'i686' | 'i386' | 'x86') \
+            pypy_download_url="https://downloads.python.org/pypy/pypy${python_version}-v${pypy_version}-linux32.tar.bz2"; \
+        ;; \
+        *) \
+            echo >&2 "error: current architecture ($unameArch) does not have a corresponding PyPy binary release"; \
+            exit 1 \
+        ;; \
     esac \
-&&  pypy_download_url=$( \
-        wget --progress=dot:giga -O- https://downloads.python.org/pypy/versions.json \
-        | jq \
-            --arg pypy_version "$pypy_version" \
-            --arg python_version "$python_version" \
-            --arg platform "$platform" \
-            --arg arch "$arch" \
-            -r \
-            ''' \
-            map( \
-                select( \
-                    .stable \
-                    and (.pypy_version | startswith($ARGS.named.pypy_version)) \
-                    and (.python_version | startswith($ARGS.named.python_version)) \
-                ) \
-            ) \
-            | sort_by(-(.pypy_version | ltrimstr($ARGS.named.pypy_version + ".") | tonumber)) \
-            | first.files[] \
-            | select(.platform == $ARGS.named.platform and .arch == $ARGS.named.arch).download_url \
-            ''' \
-    ) \
 &&  wget --progress=dot:giga -O pypy.tar.bz2 "${pypy_download_url}" \
 &&  mkdir /opt/pypy \
 &&  tar -xjC /opt/pypy --strip-components=1 -f pypy.tar.bz2 \
 &&  find /opt/pypy/lib* -depth -type d -a \( -name test -o -name tests \) -exec rm -rf '{}' + \
 &&  rm pypy.tar.bz2 \
-&&  dnf remove -y bzip2 jq \
+&&  dnf remove -y bzip2 \
 &&  ln -sv '/opt/pypy/bin/pypy3' /usr/local/bin/ \
 &&  alternatives --install /usr/bin/python3 python3 /opt/pypy/bin/python3.11 50 \
 &&  alternatives --set python3 /opt/pypy/bin/python3.11 \
